---
- name: Post-cluster add-ons
  hosts: master1
  become: true
  gather_facts: true

  roles:
    - role: k8s_ansible_deps
      tags: [deps]

    - role: cluster_addons
      tags:
        - cert-manager
        - cert-issuer
        - monitoring
        - istio
        - tempo
        - loki
        - mimir
        - alloy
        - beyla
        - train-ticket

