kubeconfig_path: /etc/kubernetes/admin.conf
ingress_class: "nginx"
storage_class: "local-path"

cert_issuer_name: "letsencrypt-http01"
acme_server_url: "https://acme-v02.api.letsencrypt.org/directory"
acme_email: "younesnikbin@gmail.com"
acme_private_key_secret: "le-account-key"

monitoring_ns: "monitoring"
prom_release_label: "prometheus-stack"
prom_repo_name: "prometheus-community"
prom_repo_url: "https://prometheus-community.github.io/helm-charts"
grafana_host: "grafana.{{ base_domain }}"
grafana_timezone: "Asia/Tehran"
grafana_admin_password: "{{ vault_grafana_admin_password }}"
grafana_pvc_size: "20Gi"
istio_scrape_interval: "10s"

istio_ns: "istio-system"
istio_repo_name: "istio"
istio_repo_url: "https://istio-release.storage.googleapis.com/charts"
istio_git_repo: "https://github.com/istio/istio.git"
istio_git_branch: "release-1.30"
istio_version: "1.30.5"
istio_dash_tmp: "/tmp/istio-{{ istio_git_branch }}"
istio_dashboards_rel_path: "manifests/addons/dashboards"
istio_grafana_folder: "Istio"
istio_stats_inclusions:
  - '.*\.upstream_rq_active$'
  - '.*\.upstream_rq_pending_active$'
  - '.*\.upstream_rq_pending_overflow$'
  - '.*\.upstream_rq_timeout$'
  - '.*\.upstream_rq_retry$'
  - '.*\.no_healthy_upstream$'
  - '.*\.downstream_cx_active$'

tempo_image: "docker.io/grafana/tempo:2.10.8"
tempo_retention: "336h"
tempo_pvc_size: "30Gi"
tempo_sampling_pct: 10.0

loki_image: "docker.io/grafana/loki:3.7.8"
loki_pvc_size: "10Gi"
loki_retention: "336h"

mimir_image: "docker.io/grafana/mimir:3.2.1"
mimir_pvc_size: "50Gi"
mimir_retention: "720h"
mimir_max_series: 1000000
mimir_ingest_rate: 500000
mimir_ingest_burst: 2000000

alloy_image: "docker.io/grafana/alloy:v1.20.0"
alloy_scrape_interval: "10s"

beyla_image: "docker.io/grafana/beyla:3.37.0"

tt_ns: "train-ticket"
tt_repo_url: "https://github.com/FudanSELab/train-ticket.git"
tt_repo_version: "0.0.4"
tt_clone_dir: "/tmp/train-ticket"
tt_enable_istio_injection: true
tt_min_replicas: 1
tt_max_replicas: 10
tt_cpu_avg_utilization: 80
tt_host: "train-ticket.{{ base_domain }}"
tt_tls_secret: "trainticket-tls"
tt_wait_retries: 60
tt_wait_delay: 5
tt_mongo_image: "mongo:4.4"
tt_app_req_cpu: "500m"
tt_app_req_mem: "512Mi"
tt_app_lim_cpu: "2"
tt_app_lim_mem: "1Gi"
tt_db_lim_cpu: "1"
tt_db_lim_mem: "512Mi"
tt_java_tool_options: "-Xmx512m"
tt_db_pvc_size: "2Gi"
tt_mongo_data_path: "/data/db"
tt_mysql_data_path: "/var/lib/mysql"
