---
- import_tasks: cert_issuer.yaml
  tags: [cert-issuer]

- import_tasks: monitoring.yaml
  tags: [monitoring]

- import_tasks: grafana_datasources.yaml
  tags: [monitoring]

- import_tasks: istio.yaml
  tags: [istio]

- import_tasks: tempo.yaml
  tags: [tempo]

- import_tasks: loki.yaml
  tags: [loki]

- import_tasks: mimir.yaml
  tags: [mimir]

- import_tasks: alloy.yaml
  tags: [alloy]

- import_tasks: beyla.yaml
  tags: [beyla]

- import_tasks: train_ticket.yaml
  tags: [train-ticket]